"""Regenerate the Phase 5 evaluation integration-test fixture.

Run from the repo root with the venv active:

    python -m tests.fixtures.evaluate._regenerate

Reuses the Phase 4 training fixture wholesale (its 36-game / 12-prediction-
parquet universe already covers every Phase 5 breakdown surface), wires it
together with a v1 ``evaluation_config.yaml``, runs ``run_evaluation_build``
into a temp directory, and copies the metric outputs into
``tests/fixtures/evaluate/expected/``. The Phase 4 training fixture's
``training_summaries`` carry real per-fold val_mae values, which the
cross-phase agreement test (``test_evaluate_metrics_cross_phase.py``)
compares against Phase 5's recomputed values.

The fixture is pinned to:
  * the Phase 2 fixture parquet bytes (regenerated by Phase 4's own fixture)
  * the Phase 4 fixture's PyTorch wheel (any retrain changes prediction bytes)
  * the matplotlib wheel that produced the expected PNGs (PNGs are not
    checked in; existence is asserted but byte-identity is not — EV-NF-02)

The build_timestamp_utc and git_commit fields of the resulting evaluation
manifest are blanked in the snapshot so byte-equality tests pin to the rest.

Outputs:
    tests/fixtures/evaluate/raw_phase2/   (copied from train fixture)
    tests/fixtures/evaluate/raw_phase3/   (copied from train fixture)
    tests/fixtures/evaluate/raw_phase4/   (copied from train fixture)
    tests/fixtures/evaluate/raw/evaluation_config.yaml
    tests/fixtures/evaluate/expected/metrics_headline.json
    tests/fixtures/evaluate/expected/breakdowns/*.parquet
    tests/fixtures/evaluate/expected/evaluation_manifest.json
"""

from __future__ import annotations

import json
import pathlib
import shutil
import sys

from nflpredictor.evaluate.outputs import (
    BREAKDOWNS_DIRNAME,
    EVALUATION_DIRNAME,
    EVALUATION_MANIFEST_BASENAME,
    METRICS_HEADLINE_BASENAME,
)
from nflpredictor.evaluate.pipeline import (
    EVALUATION_CONFIG_BASENAME,
    run_evaluation_build,
)
from nflpredictor.evaluate.sources import (
    PHASE2_FEATURES_FLAT_BASENAME,
    PHASE2_FEATURES_POS_BASENAME,
    PHASE2_MANIFEST_BASENAME,
    PHASE2_VOCAB_BASENAME,
    PHASE3_MANIFEST_BASENAME,
    PHASE3_SPLITS_BASENAME,
    PHASE4_MANIFEST_BASENAME,
    PHASE4_PREDICTIONS_DIRNAME,
)


REPO_ROOT = pathlib.Path(__file__).resolve().parents[3]
TRAIN_FIXTURE = REPO_ROOT / "tests" / "fixtures" / "train"
EVAL_FIXTURE = pathlib.Path(__file__).parent

RAW_PHASE2 = EVAL_FIXTURE / "raw_phase2"
RAW_PHASE3 = EVAL_FIXTURE / "raw_phase3"
RAW_PHASE4 = EVAL_FIXTURE / "raw_phase4"
RAW_CONFIG = EVAL_FIXTURE / "raw"
EXPECTED = EVAL_FIXTURE / "expected"


PHASE2_FILES: tuple[str, ...] = (
    PHASE2_FEATURES_FLAT_BASENAME,
    PHASE2_FEATURES_POS_BASENAME,
    PHASE2_VOCAB_BASENAME,
    PHASE2_MANIFEST_BASENAME,
)
PHASE3_FILES: tuple[str, ...] = (PHASE3_SPLITS_BASENAME, PHASE3_MANIFEST_BASENAME)


def _wipe_and_mkdir(d: pathlib.Path) -> None:
    if d.exists():
        shutil.rmtree(d)
    d.mkdir(parents=True)


def _copy_train_fixture() -> None:
    """Copy the Phase 4 train fixture into the eval fixture's raw_phase{2,3,4} dirs."""
    for name in PHASE2_FILES:
        shutil.copy2(TRAIN_FIXTURE / "raw_phase2" / name, RAW_PHASE2 / name)
    for name in PHASE3_FILES:
        shutil.copy2(TRAIN_FIXTURE / "raw_phase3" / name, RAW_PHASE3 / name)
    # Phase 4: training_manifest.json + every prediction parquet.
    pred_dir = RAW_PHASE4 / PHASE4_PREDICTIONS_DIRNAME
    pred_dir.mkdir(parents=True, exist_ok=True)
    for p in sorted((TRAIN_FIXTURE / "expected" / PHASE4_PREDICTIONS_DIRNAME).glob("*.parquet")):
        shutil.copy2(p, pred_dir / p.name)
    shutil.copy2(
        TRAIN_FIXTURE / "expected" / PHASE4_MANIFEST_BASENAME,
        RAW_PHASE4 / PHASE4_MANIFEST_BASENAME,
    )


def _ship_evaluation_config() -> None:
    """Copy the v1 evaluation_config.yaml from the main raw/ dir."""
    shutil.copy2(
        REPO_ROOT / "Data" / "raw" / EVALUATION_CONFIG_BASENAME,
        RAW_CONFIG / EVALUATION_CONFIG_BASENAME,
    )


def _stage_processed_dir(working: pathlib.Path) -> None:
    """Lay every Phase 2 / Phase 3 / Phase 4 input into one processed dir."""
    working.mkdir(parents=True, exist_ok=True)
    for name in PHASE2_FILES:
        shutil.copy2(RAW_PHASE2 / name, working / name)
    for name in PHASE3_FILES:
        shutil.copy2(RAW_PHASE3 / name, working / name)
    shutil.copy2(RAW_PHASE4 / PHASE4_MANIFEST_BASENAME, working / PHASE4_MANIFEST_BASENAME)
    pred_dst = working / PHASE4_PREDICTIONS_DIRNAME
    pred_dst.mkdir(exist_ok=True)
    for p in sorted((RAW_PHASE4 / PHASE4_PREDICTIONS_DIRNAME).glob("*.parquet")):
        shutil.copy2(p, pred_dst / p.name)


def _snapshot_expected(eval_dir: pathlib.Path) -> None:
    """Copy headline JSON + breakdown parquets to expected/; blank manifest timestamp + git_commit."""
    # Wipe and recreate the expected dirs.
    _wipe_and_mkdir(EXPECTED)
    (EXPECTED / BREAKDOWNS_DIRNAME).mkdir()

    shutil.copy2(eval_dir / METRICS_HEADLINE_BASENAME, EXPECTED / METRICS_HEADLINE_BASENAME)
    for p in sorted((eval_dir / BREAKDOWNS_DIRNAME).glob("*.parquet")):
        shutil.copy2(p, EXPECTED / BREAKDOWNS_DIRNAME / p.name)

    manifest = json.loads((eval_dir / EVALUATION_MANIFEST_BASENAME).read_text())
    manifest["build_timestamp_utc"] = "FIXTURE_TIMESTAMP"
    manifest["git_commit"] = "FIXTURE_GIT_COMMIT"
    with (EXPECTED / EVALUATION_MANIFEST_BASENAME).open("w", encoding="utf-8") as f:
        json.dump(manifest, f, sort_keys=True, indent=2)
        f.write("\n")


def build_fixture() -> None:
    for d in (RAW_PHASE2, RAW_PHASE3, RAW_PHASE4, RAW_CONFIG):
        _wipe_and_mkdir(d)
    _copy_train_fixture()
    _ship_evaluation_config()

    # Run the evaluation build into a working processed dir so the expected
    # outputs are pinned to the same Phase 4 SHAs the test will see at runtime.
    working = EVAL_FIXTURE / "_working"
    if working.exists():
        shutil.rmtree(working)
    working.mkdir()
    try:
        _stage_processed_dir(working)
        run_evaluation_build(RAW_CONFIG, working, repo_dir=REPO_ROOT)
        _snapshot_expected(working / EVALUATION_DIRNAME)
    finally:
        if working.exists():
            shutil.rmtree(working)

    print(
        "Regenerated Phase 5 fixture:",
        *(p.relative_to(REPO_ROOT) for p in sorted(EVAL_FIXTURE.rglob("*")) if p.is_file()),
        sep="\n  ",
        file=sys.stderr,
    )


if __name__ == "__main__":
    build_fixture()
